# Generated by Django 5.0.14 on 2025-07-16 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmhIntranetApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bmhvmcs',
            options={'verbose_name_plural': 'BMH Vision, Mission, & Core Values'},
        ),
        migrations.RemoveField(
            model_name='bmhcalendars',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='bmhcalendars',
            name='start_time',
        ),
    ]
